# Generated by Django 3.2.5 on 2021-07-29 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salonapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='appointmentdate',
            field=models.TextField(blank=True, default=None, max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.TextField(blank=True, default=None, max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='firstname',
            field=models.CharField(blank=True, default=None, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='lastname',
            field=models.TextField(blank=True, default=None, max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='service',
            field=models.TextField(blank=True, default=None, max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='telephone',
            field=models.TextField(blank=True, default=None, max_length=20000, null=True),
        ),
    ]
