# Generated by Django 3.2.5 on 2021-08-01 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salonapp', '0002_auto_20210801_0023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameoncard', models.CharField(blank=True, default=None, max_length=2000, null=True)),
                ('email', models.TextField(blank=True, default=None, max_length=20000, null=True)),
                ('service', models.TextField(blank=True, default=None, max_length=20000, null=True)),
                ('telephone', models.TextField(blank=True, default=None, max_length=20000, null=True)),
                ('appointmentdate', models.TextField(blank=True, default=None, max_length=20000, null=True)),
                ('time', models.DateTimeField(blank=True, default=None, max_length=20000, null=True)),
                ('creditcardnumber', models.TextField(blank=True, default=None, max_length=20000, null=True)),
                ('cvv', models.TextField(blank=True, default=None, max_length=20000, null=True)),
                ('expiration', models.TextField(blank=True, default=None, max_length=20000, null=True)),
                ('billingaddress', models.TextField(blank=True, default=None, max_length=20000, null=True)),
            ],
        ),
    ]
